### ISSUE TITLE
Ready for Grading Assignment Week 8 Functions

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#12]

**Comment by cethenmc** [comment]
Nice work.  8 of 8.  I will mention that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, you may want to consider modifying your tempconversion.py script to run that way.

**Comment by cethenmc** [comment]
Oh, one other note.  This should have been in the week9 folder, not week8.
