### ISSUE TITLE
Week11 Arguments Lab is Ready For Grading

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#13]

**Comment by cethenmc** [comment]
Hi, Viktoryia.  Nice work!

One item here did not meet the requirements of the lab.  As a result, I recorded a 7.5 of 8 for now.  Please let me know if you would like to keep the 7.5 of 8 or resubmit corrections to achieve full points.

I can issue this "./arguments.py" without any arguments.  If the lab were followed, that would fail because the integer is not supplied.

Please remember to submit Week10, as well.  I don't see that you ever submitted an Issue for Week10.  

Thanks.

Chris

**Comment by vanufrovich-matc** [comment]
Hi Chris,

Week10 lab has just been submitted, thanks for the reminder!
I will 7.5 grade, thanks!

Thank you,
Viktoryia

**Comment by cethenmc** [comment]
Thanks, Viktoryia!  I will lock in 7.5 on this one, and close this ticket.
