### ISSUE TITLE
Ready for grading assignment week5

### ISSUE THREAD

**Issue by vanufrovich-matc** [madisoncollege-it-programs/python-scripting-vanufrovich-matc#3]

**Comment by cethenmc** [comment]
You are missing answers in this script.

#1B remains unanswered.
#1C good be a little better definition
#3 is quite off in that there is not a cumulative saving of each line to a variable.
Also, missing author and script description at the top

Please rework and ask questions if something doesn't make sense.

Thanks.

Chris

PS - Recording 5 of 8 until this had been corrected,

**Comment by cethenmc** [comment]
Viktoryia.  Please book some time with me if you would like to go through this one.  I would be happy to help!

**Comment by cethenmc** [comment]
Viktoryia - Nice way of doing this one, but it is not doing what was asked still.  It did ask you to 'read' it using one of the read functions.  Also, 3B was answered.  As a result, I will add one more point to the score.  Please book me if you want to just take 15 minutes to run through it together and have you resubmit for full credit, or if you would like to try one more time on your own.

**Comment by cethenmc** [comment]
Hi, Viktoryia.  Please let me know if you intend to keep this 6 of 8 score or if you intend to push corrections to Git Hub for this one.  Thanks!  Chris

**Comment by vanufrovich-matc** [comment]
Hi Chris. I've pushed my changes to Github. 
Thank you!

**Comment by cethenmc** [comment]
Thank you, Viktoryia.  I will likely look at these tomorrow or first thing Monday morning.

Chris

[signature_146958654]
Chris Ethen | Information Technology Instructor
Madison College | 1701 Wright Street | Madison, WI  53704
P: 1.608.616.1099 | ***@***.******@***.***>

**Comment by cethenmc** [comment]
Hi, Viktoryia.  In 1, you ended up overwriting the explanation of the len() in that one.  You are supposed to explain what len() gives, and then what read() gives and when you'd use it.  You did the read() explanation, but not the len() explanation.

2 was well done!

3 was not done as requested.  The requirements ask you to save the full contents into a variable by **reading** one line at a time.  Because you did not do this, you are explaining the wrong read function.

Unfortunately, I cannot add more points than 6 of 8.  Would you like to set up a quick meeting to walk through this one?  I would be more than happy to help clarify what we are seeking.  Otherwise, if you would like to keep the 6 of 8, then please let me know in this ticket.

Thanks.

Chris

**Comment by vanufrovich-matc** [comment]
Hi Chris, 
I will 6 of 8, thank you!!

**Comment by cethenmc** [comment]
Thank you, Viktoryia.
